image: grifart/php8.1-with-all-modules-and-various-tools


# STAGES

stages:
- build
- test



# BUILDS

# composer

.build-composer-template: &build-composer-template
  stage: build

  artifacts:
    expire_in: 2 hours
    name: "${CI_BUILD_REF_NAME}_${CI_BUILD_NAME}"
    paths:
    - vendor

build.composer.dev:
  <<: *build-composer-template

  script:
  - composer install --no-interaction --ansi

build.composer:
  <<: *build-composer-template

  script:
  - composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader --ansi




# TESTS


# php lint

test.php-syntax-check:
  stage: test

  script:
  - composer require php-parallel-lint/php-parallel-lint
  - vendor/bin/parallel-lint src


# php stan

test.phpstan:
  stage: test

  dependencies:
  - build.composer.dev

  script:
  - composer run phpstan


# tests

.test.tests: &test-tests
  stage: test

  dependencies: []

  before_script:
    - composer install --no-interaction --ansi

  script:
  - composer run test

  artifacts:
    expire_in: 15 minutes
    paths:
    - log
    - src # can contain assertion diffs
    when: on_failure


test.tests.php71:
  <<: *test-tests
  image: grifart/php7.1-with-gulp-and-all-php-modules

test.tests.php71.oldDeps:
  <<: *test-tests
  before_script:
    - composer update --prefer-lowest --no-interaction --ansi
  image: grifart/php7.1-with-gulp-and-all-php-modules



test.tests.php72:
  <<: *test-tests
  image: grifart/php7.2-with-gulp-and-all-php-modules

test.tests.php72.oldDeps:
  <<: *test-tests
  before_script:
    - composer update --prefer-lowest --no-interaction --ansi
  image: grifart/php7.2-with-gulp-and-all-php-modules



test.tests.php73:
  <<: *test-tests
  image: grifart/php7.3-with-gulp-and-all-php-modules

test.tests.php73.oldDeps:
  <<: *test-tests
  before_script:
    - composer update --prefer-lowest --no-interaction --ansi
  image: grifart/php7.3-with-gulp-and-all-php-modules



test.tests.php74:
  <<: *test-tests
  image: grifart/php7.4-with-gulp-and-all-php-modules

test.tests.php74.oldDeps:
  <<: *test-tests
  before_script:
    - composer update --prefer-lowest --no-interaction --ansi
  image: grifart/php7.4-with-gulp-and-all-php-modules



test.tests.php80:
  <<: *test-tests
  image: grifart/php8.0-with-all-modules-and-various-tools

test.tests.php80.oldDeps:
  <<: *test-tests
  before_script:
    - composer update --prefer-lowest --no-interaction --ansi
  image: grifart/php8.0-with-all-modules-and-various-tools



test.tests.php81:
  <<: *test-tests
  image: grifart/php8.1-with-all-modules-and-various-tools

test.tests.php81.oldDeps:
  <<: *test-tests
  before_script:
    - composer update --prefer-lowest --no-interaction --ansi
  image: grifart/php8.1-with-all-modules-and-various-tools